# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('party_id', models.CharField(max_length=1)),
                ('new_column', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=50)),
            ],
        ),
    ]
