# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('m_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(max_length=50)),
            ],
        ),
    ]
