# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='l_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='m_name',
            new_name='middle_name',
        ),
    ]
