# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_person_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PageHeaderAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PageNavAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_id', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=50)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PageHeaderAccess')),
            ],
        ),
        migrations.AddField(
            model_name='alluseraccess',
            name='access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PageNavAccess'),
        ),
    ]
