# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170506_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageheaderaccess',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pagenavaccess',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
