# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170508_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluseraccess',
            name='access_level',
            field=models.IntegerField(default=1),
        ),
    ]
