# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alluseraccess_access_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alluseraccess',
            name='access_level',
        ),
    ]
