# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alluseraccess_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alluseraccess',
            name='access_level',
            field=models.CharField(default='', max_length=4),
        ),
    ]
