# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_accountaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alluseraccess',
            name='access',
        ),
        migrations.DeleteModel(
            name='AllUserAccess',
        ),
    ]
