# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20170513_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(default='', max_length=4)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PageNavAccess')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person')),
            ],
        ),
    ]
