# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alluseraccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountaccess',
            name='access',
        ),
        migrations.RemoveField(
            model_name='accountaccess',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountAccess',
        ),
    ]
