# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_accountaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountaccess',
            name='access',
        ),
        migrations.RemoveField(
            model_name='accountaccess',
            name='header_access',
        ),
        migrations.DeleteModel(
            name='AccountAccess',
        ),
    ]
