# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_account_accountaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='person',
        ),
    ]
