# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_party_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Party'),
        ),
    ]
