# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
