# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170603_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
    ]
