# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20170613_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmodules',
            name='url',
            field=models.CharField(default='error', max_length=200),
        ),
    ]
