# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_appmodules_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessonaccessgroup',
            old_name='group',
            new_name='group_acces',
        ),
    ]
