# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20170617_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessonaccessgroup',
            old_name='group_acces',
            new_name='group_access',
        ),
    ]
