# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20170617_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyGroupOnCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AppModules')),
                ('group_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GroupAccess')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Party')),
            ],
        ),
    ]
