# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_partygrouponcustom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partygrouponcustom',
            name='app_module',
        ),
        migrations.RemoveField(
            model_name='partygrouponcustom',
            name='group_access',
        ),
        migrations.RemoveField(
            model_name='partygrouponcustom',
            name='party',
        ),
        migrations.DeleteModel(
            name='PartyGroupOnCustom',
        ),
    ]
