# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_partygrouponcustom'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('thru_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GLAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalGLAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('thru_date', models.DateField()),
                ('accounting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountingPeriod')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GLAccount')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Party')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='glaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GLAccountType'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='period_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PeriodType'),
        ),
    ]
